// <auto-generated />
using System;
using Extermination.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Extermination.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Extermination.Models.ServiceRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PestType")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("PreferredDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ServiceRequests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Maple Street, Springfield, IL 62701",
                            CreatedAt = new DateTime(2024, 6, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            CustomerName = "Alice Johnson",
                            Description = "Ant trail coming in through kitchen window.",
                            Email = "alice@example.com",
                            PestType = 0,
                            Phone = "555-123-4567",
                            PreferredDate = new DateTime(2024, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 2
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Oak Avenue, Shelbyville, IL 62565",
                            CreatedAt = new DateTime(2024, 6, 28, 10, 30, 0, 0, DateTimeKind.Utc),
                            CustomerName = "Bob Martinez",
                            Description = "Hearing noises in the attic at night.",
                            Email = "bob@example.com",
                            PestType = 5,
                            Phone = "555-987-6543",
                            PreferredDate = new DateTime(2024, 7, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Pine Road, Capital City, IL 62702",
                            CreatedAt = new DateTime(2024, 7, 1, 14, 0, 0, 0, DateTimeKind.Utc),
                            CustomerName = "Carol White",
                            Description = "Noticed wood damage in basement beams.",
                            Email = "carol@example.com",
                            PestType = 7,
                            Phone = "555-246-8013",
                            Status = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
